### PR TITLE
Sujith isbadversion

### PR DESCRIPTION
**Pull request by Sujith1910**
basic binary search problem with a small twist.

### CODE REVIEW

**Comment by vinay080** [comment]
Looks like the code/problem both arent in this PR.. i merged all other branches to keep it clean. can you pull latest from master, rebase in your branch and push?

**Comment by Sujith1910** [comment]
not sure about the rebase command. I might mess it up again lol.
just give me the command please

**Comment by vinay080** [comment]
Lets do this.. git checkout master.. gill pull and then create new branch for this change and submit

**Comment by Sujith1910** [comment]
ok will try.

**Pull request closed without merging**
